### ISSUE TITLE
extractor.extract_reply_screen_name fails if there is no screen name

### ISSUE THREAD

**Issue by gnunicorn** [dryan/twitter-text-py#1]
The API Docs state that it will return "None" but currently it fails with 

 File "[...]/eggs/twitter_text_py-1.0.1-py2.5.egg/twitter_text/extractor.py", line 65, in extract_reply_screen_name
    possible_screen_name = REGEXEN['extract_reply'].match(self.text).group(0)
AttributeError: 'NoneType' object has no attribute 'group'

Looking into the code I see that this behaviour is not catched as the documentations says but instead will always happen when there is no match. Either update the documentation or put an try: .. except AttributeError: return None around it pls.

**Comment by dryan** [comment]
This was corrected in commit 60b80771fba8c07d65e68150d563c4456bec4890.
