### ISSUE TITLE
Not recognizing URLs like `example.com?foo=bar`

### ISSUE THREAD

**Issue by swinton** [dryan/twitter-text-py#22]
twitter-text-py does not recognize URLs like `example.com?foo=bar`, it parses these as just `example.com`, dropping the query string:

``` python
import twitter_text as parser
parsed = parser.Extractor("www.example.com?foo=bar example.com?foo=bar")
parsed.extract_urls()  # [u'www.example.com', u'example.com']
```

**Comment by swinton** [comment]
Note that, although most web servers will recognize URLs written in this way, they aren't strictly speaking valid URLs, since they have no path component, i.e. `example.com?foo=bar` should strictly be represented as `example.com/?foo=bar`. When written in this way, they are extracted correctly by twitter-text-py:

``` python
import twitter_text as parser
parsed = parser.Extractor("www.example.com/?foo=bar example.com/?foo=bar")
parsed.extract_urls()  # [u'www.example.com/?foo=bar', u'example.com/?foo=bar']
```

Also, note, that Twitter's official OS X client also fails to recognize URLs written in this way:

 ![](http://i.imgur.com/gSDkfT1.png)

**Comment by dryan** [comment]
We track the official Twitter library for this; unless they change how they handle this situation neither will we.
