### ISSUE TITLE
1.0.4 on PyPI

### ISSUE THREAD

**Issue by j4mie** [dryan/twitter-text-py#8]
Thanks for merging my PR.

There don't seem to be any downloads for 1.0.4 on PyPI: http://pypi.python.org/pypi/twitter-text-py/1.0.4 (compare with http://pypi.python.org/pypi/twitter-text-py/1.0.3 )

Did you do `python setup.py sdist upload` (or similar)?

Thanks!

**Comment by dryan** [comment]
I did. On the admin side it shows 1.0.4. I'm assuming it takes some time to
get updated.

On Tuesday, December 20, 2011, Jamie Matthews <
reply@reply.github.com>
wrote:

**Comment by j4mie** [comment]
It's still not working, unfortunately. No idea what's wrong :(

```
$ mkvirtualenv twitter-text-py
$ pip install twitter-text-py
$ pip freeze | grep twitter-text-py
twitter-text-py==1.0.3
```

**Comment by kayluhb** [comment]
This is still not available a year later.
